### ISSUE TITLE
/sign ui clears signs

### ISSUE THREAD

**Issue by TeddyLovesYou88** [Deltik/SignEdit#30] opened 2022-04-30 12:51 UTC
is it normal when you do /sign ui it clears the sign with words written on it?

**Comment by Deltik** [comment] 2022-04-30 13:05
You mean no matter what you put into the sign editor, the sign gets cleared?  No, that's not expected.

Try disabling other plugins that might interfere with signs to see if the problem persists.  If you believe it's a bug in SignEdit for Bukkit, please provide steps to reproduce the bug.

**Comment by TeddyLovesYou88** [comment] 2022-04-30 13:07
I had a sign saying Redstone Items and when I did /sign ui  the sign got cleared.

**Comment by TeddyLovesYou88** [comment] 2022-04-30 13:14
> I had a sign saying Redstone Items and when I did /sign ui the sign got cleared.

is that normal? 
Is it doing it to you when you do /sign ui when you have something written on the sign?  
If its not then I can have a better idea on fixing the issue by removing some plugins.

**Comment by Deltik** [comment] 2022-04-30 15:22
No, `/sign ui` prefills the client-side sign editor with the existing sign text unless you're on Minecraft 1.16.1.

Does the sign text disappear after closing the sign editor or at the same time the sign editor opens?

**Comment by TeddyLovesYou88** [comment] 2022-04-30 15:36
it clears the sign when i open the sign editor

**Comment by Deltik** [comment] 2022-05-01 05:06
The only known bug that causes the sign editor to open without sign contents is [MC-192263](https://web.archive.org/web/20200714051840/https://bugs.mojang.com/browse/MC-192263?focusedCommentId=759126&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-759126), which affected Minecraft 1.16.1 only.

For now, I'll close this issue because I can't make the issue happen on Minecraft 1.18.2 and SignEdit for Bukkit `= 1.13.7`, but I'll reopen it if you can show me how to reproduce it.

Helpful information to include:
* Bukkit software and version
* SignEdit for Bukkit version
* All other server plugins and versions
* Minecraft client version

**Closed as completed by Deltik** 2022-05-01 05:06 UTC
Labels: invalid
