### ISSUE TITLE
Problem with right click in sign with commands

### ISSUE THREAD

**Issue by aurel85** [Deltik/SignEdit#36] opened 2023-07-08 13:56 UTC
Hi,

SignEdit Version: 1.14.0-beta3
Server Version: git-Paper-67 (MC: 1.20.1)

With the last version when the players right click on a sign that works with a command (ServerSigns) nothing happens because the plugin wants to modify them. On my server without this plugin there is no problem. I am therefore obliged to /sign wax all my signs with commands but on my side I can no longer modify them at all. Would it be possible to fix this so that commands in a panel take precedence over modification especially when the player can't modify the panel because he doesn't have all the permissions.

Error in the console and drop in tps (here they are signs with commands but in a vanilla way (command block), with ServerSigns there is not this error, they can just do nothing) : https://pastebin.com/K85HBUhF

Thank you in advance.

**Comment by Deltik** [comment] 2023-07-08 14:24
I already tried dropping the "priority" of the right-click handling to the lowest so that other plugins can take precedence, but it sounds like there are more issues.  I'll investigate further.

**Comment by seema84** [comment] 2023-07-10 09:59
I can confirm this problem.

**Comment by Deltik** [comment] 2023-07-10 11:55
I have a partial fix in [**SignEdit-1.14.0-beta3-1-g79ed0ab-SNAPSHOT.zip**](https://github.com/Deltik/SignEdit/files/12001500/SignEdit-1.14.0-beta3-1-g79ed0ab-SNAPSHOT.zip), which should resolve the problem of Spigot crashing shortly after right-mouse clicking a sign.

I'm still investigating the plugin compatibility issue.

**Comment by Deltik** [comment] 2023-07-13 10:31
@aurel85 and @seema84: Thanks for reporting this bug!

It has _probably_ been fixed in [SignEdit for Bukkit v1.14.0-beta4](https://github.com/Deltik/SignEdit/releases/tag/v1.14.0-beta4), which you can directly download [here](https://github.com/Deltik/SignEdit/releases/download/v1.14.0-beta4/SignEdit-1.14.0-beta4.jar).

**Comment by seema84** [comment] 2023-07-13 12:19
Thanks for the quick update. I will try it out soon.

**Comment by seema84** [comment] 2023-07-13 12:26
now (with version 1.14.0-beta4) i get this error (on rightclick)

`[Server thread/ERROR]: java.lang.NullPointerException: Cannot invoke "org.bukkit.inventory.ItemStack.getType()" because the return value of "org.bukkit.event.player.PlayerInteractEvent.getItem()" is null
	at SignEdit-1.14.0-beta4.jar//net.deltik.mc.signedit.listeners.CoreSignEditListener.onRightClickSign(CoreSignEditListener.java:1132)
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor578.execute(Unknown Source)
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77)
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77)
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54)
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126)
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615)
	at org.bukkit.craftbukkit.v1_20_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:566)
	at net.minecraft.server.level.PlayerInteractManager.a(PlayerInteractManager.java:537)
	at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1960)
	at net.minecraft.network.protocol.game.PacketPlayInUseItem.a(PacketPlayInUseItem.java:37)
	at net.minecraft.network.protocol.game.PacketPlayInUseItem.a(PacketPlayInUseItem.java:9)
	at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$0(PlayerConnectionUtils.java:51)
	at net.minecraft.server.TickTask.run(TickTask.java:18)
	at net.minecraft.util.thread.IAsyncTaskHandler.d(IAsyncTaskHandler.java:153)
	at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(IAsyncTaskHandlerReentrant.java:24)
	at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1339)
	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197)
	at net.minecraft.util.thread.IAsyncTaskHandler.x(IAsyncTaskHandler.java:126)
	at net.minecraft.server.MinecraftServer.bg(MinecraftServer.java:1316)
	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1309)
	at net.minecraft.util.thread.IAsyncTaskHandler.c(IAsyncTaskHandler.java:136)
	at net.minecraft.server.MinecraftServer.p_(MinecraftServer.java:1287)
	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1175)
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318)
	at java.base/java.lang.Thread.run(Thread.java:833)`

**Comment by Deltik** [comment] 2023-07-13 12:27
Okay, I'll fix this shortly.  Hang on!

**Comment by Deltik** [comment] 2023-07-13 12:42
@seema84: That new bug (regression) has been fixed in [SignEdit for Bukkit v1.14.0-beta5](https://github.com/Deltik/SignEdit/releases/tag/v1.14.0-beta5), which you can directly download [here](https://github.com/Deltik/SignEdit/releases/download/v1.14.0-beta5/SignEdit-1.14.0-beta5.jar).

**Closed as completed by Deltik** 2023-07-13 12:42 UTC
Labels: bug

**Comment by seema84** [comment] 2023-07-13 12:51
The Beta 5 version seems to work.

**Comment by Deltik** [comment] 2023-07-13 12:52
Excellent!  Please let me know (in a new issue) if you encounter any more bugs.
